public class Admin extends Person{

    // Attributes
    private String department; // Department of the admin
    private int experience;    // Years of experience of the admin
    private int revenue;       // Revenue generated by the admin

    /**
     * Default constructor.
     * Constructs an Admin object with default values.
     */
    public Admin() {
    }

    /**
     * Parameterized constructor.
     * Constructs an Admin object with specified values.
     * @param department The department of the admin
     * @param experience Years of experience of the admin
     * @param revenue Revenue generated by the admin
     */
    public Admin(String department, int experience, int revenue) {
        this.department = department;
        this.experience = experience;
        this.revenue = revenue;
    }

    // Getters and setters for department, experience, and revenue attributes

    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

    public int getExperience() {
        return experience;
    }

    public void setExperience(int experience) {
        this.experience = experience;
    }

    public int getRevenue() {
        return revenue;
    }

    public void setRevenue(int revenue) {
        this.revenue = revenue;
    }
}
