
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hossa
 */
public class gui_addFlight extends javax.swing.JFrame {

    /**
     * Creates new form gui_addFlight
     */
    public gui_addFlight() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLableAddFlight = new javax.swing.JLabel();
        JFlightNumber = new javax.swing.JTextField();
        jDepartureLcation = new javax.swing.JTextField();
        jArrivalLocation = new javax.swing.JTextField();
        jDepartureTime = new javax.swing.JTextField();
        jArrivalTime = new javax.swing.JTextField();
        jStatus = new javax.swing.JTextField();
        jOrigin = new javax.swing.JTextField();
        jDistance = new javax.swing.JTextField();
        Create = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jDestination = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 45, 65));

        jLableAddFlight.setBackground(new java.awt.Color(0, 0, 0));
        jLableAddFlight.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLableAddFlight.setForeground(new java.awt.Color(95, 210, 195));
        jLableAddFlight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLableAddFlight.setText("Add Flight");
        jLableAddFlight.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        JFlightNumber.setBackground(new java.awt.Color(34, 45, 65));
        JFlightNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JFlightNumber.setForeground(new java.awt.Color(255, 255, 255));
        JFlightNumber.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        JFlightNumber.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Flight Number", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        JFlightNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JFlightNumberMouseClicked(evt);
            }
        });
        JFlightNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JFlightNumberActionPerformed(evt);
            }
        });

        jDepartureLcation.setBackground(new java.awt.Color(34, 45, 65));
        jDepartureLcation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDepartureLcation.setForeground(new java.awt.Color(255, 255, 255));
        jDepartureLcation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDepartureLcation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departure Location", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jDepartureLcation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDepartureLcationMouseClicked(evt);
            }
        });
        jDepartureLcation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartureLcationActionPerformed(evt);
            }
        });

        jArrivalLocation.setBackground(new java.awt.Color(34, 45, 65));
        jArrivalLocation.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jArrivalLocation.setForeground(new java.awt.Color(255, 255, 255));
        jArrivalLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jArrivalLocation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arrival Location", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jArrivalLocation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jArrivalLocationMouseClicked(evt);
            }
        });
        jArrivalLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArrivalLocationActionPerformed(evt);
            }
        });

        jDepartureTime.setBackground(new java.awt.Color(34, 45, 65));
        jDepartureTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDepartureTime.setForeground(new java.awt.Color(255, 255, 255));
        jDepartureTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDepartureTime.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Departure Time", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jDepartureTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDepartureTimeMouseClicked(evt);
            }
        });
        jDepartureTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDepartureTimeActionPerformed(evt);
            }
        });

        jArrivalTime.setBackground(new java.awt.Color(34, 45, 65));
        jArrivalTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jArrivalTime.setForeground(new java.awt.Color(255, 255, 255));
        jArrivalTime.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jArrivalTime.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Arrival Time", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jArrivalTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jArrivalTimeMouseClicked(evt);
            }
        });
        jArrivalTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jArrivalTimeActionPerformed(evt);
            }
        });

        jStatus.setBackground(new java.awt.Color(34, 45, 65));
        jStatus.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jStatus.setForeground(new java.awt.Color(255, 255, 255));
        jStatus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Status", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStatusMouseClicked(evt);
            }
        });
        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        jOrigin.setBackground(new java.awt.Color(34, 45, 65));
        jOrigin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jOrigin.setForeground(new java.awt.Color(255, 255, 255));
        jOrigin.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jOrigin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Origin", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jOrigin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jOriginMouseClicked(evt);
            }
        });
        jOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOriginActionPerformed(evt);
            }
        });

        jDistance.setBackground(new java.awt.Color(34, 45, 65));
        jDistance.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDistance.setForeground(new java.awt.Color(255, 255, 255));
        jDistance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDistance.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Distance", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jDistance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDistanceMouseClicked(evt);
            }
        });
        jDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDistanceActionPerformed(evt);
            }
        });

        Create.setBackground(new java.awt.Color(95, 210, 195));
        Create.setText("Create");
        Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateActionPerformed(evt);
            }
        });

        Back.setBackground(new java.awt.Color(95, 210, 195));
        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        jDestination.setBackground(new java.awt.Color(34, 45, 65));
        jDestination.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jDestination.setForeground(new java.awt.Color(255, 255, 255));
        jDestination.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDestination.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destination ", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jDestination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDestinationMouseClicked(evt);
            }
        });
        jDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDestinationActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageedit_9_6022422384 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JFlightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jArrivalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLableAddFlight, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDepartureLcation))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Create, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLableAddFlight)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JFlightNumber)
                            .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDepartureLcation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jDepartureTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jArrivalTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jArrivalLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Back, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                            .addComponent(Create, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDestinationActionPerformed

    private void jDestinationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDestinationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jDestinationMouseClicked

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        try {
            new gui_admin().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {
            // Handle the exception appropriately, for example, logging it
            e.printStackTrace();
        }
    }//GEN-LAST:event_BackActionPerformed

    private void CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateActionPerformed
        try {
            ManageFlight flight = new ManageFlight();

            String flightNumber = JFlightNumber.getText();
            String departureLocation = jDepartureLcation.getText();
            String arrivalLocation = jArrivalLocation.getText();
            String departureTime = jDepartureTime.getText();
            String arrivalTime = jArrivalTime.getText();
            String status = jStatus.getText();
            String origin = jOrigin.getText();
            String destination = jDestination.getText();
            double distance = Double.parseDouble(jDistance.getText());

            List<Seat> seatsForFlight = new ArrayList<>() {
                {
                    add(new Seat(1, true, "Business", -1)); //true = available
                    add(new Seat(2, true, "Business", -1));
                    add(new Seat(3, true, "VIP", -1));
                    add(new Seat(4, true, "VIP", -1));
                    add(new Seat(5, true, "Business", -1));
                    add(new Seat(6, true, "VIP", -1));
                    add(new Seat(7, true, "Business", -1));
                }
            };

            Flight fly = flight.createFlight(flightNumber, departureLocation, arrivalLocation, departureTime, arrivalTime, status, origin, destination, distance, seatsForFlight);

            String filePath = "src/Flights.txt";
            ObjectMapper objectMapper = new ObjectMapper();
            String json = objectMapper.writeValueAsString(fly);

            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            content = content.trim();
            if (content.endsWith("]")) {
                if (content.length() > 1) {
                    content = content.substring(0, content.length() - 1).trim();
                    if (!content.isEmpty()) {
                        content += ",";
                    }
                }
                // Append the new JSON object
                content += json;

                content += "\n]";
            }

            System.out.println(content);

            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
            writer.write(content);
            writer.close();
            System.out.println("New JSON object added to the array successfully.");

        } catch (IOException ex) {
            Logger.getLogger(gui_addFlight.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CreateActionPerformed

    private void jDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDistanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDistanceActionPerformed

    private void jDistanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDistanceMouseClicked
        jDistance.setText("");
    }//GEN-LAST:event_jDistanceMouseClicked

    private void jOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOriginActionPerformed

    private void jOriginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jOriginMouseClicked
        jOrigin.setText("");
    }//GEN-LAST:event_jOriginMouseClicked

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatusActionPerformed

    private void jStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStatusMouseClicked
        jStatus.setText("");
    }//GEN-LAST:event_jStatusMouseClicked

    private void jArrivalTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArrivalTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jArrivalTimeActionPerformed

    private void jArrivalTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jArrivalTimeMouseClicked
        jArrivalTime.setText("");
    }//GEN-LAST:event_jArrivalTimeMouseClicked

    private void jDepartureTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartureTimeActionPerformed

    }//GEN-LAST:event_jDepartureTimeActionPerformed

    private void jDepartureTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDepartureTimeMouseClicked
        jDepartureTime.setText("");
    }//GEN-LAST:event_jDepartureTimeMouseClicked

    private void jArrivalLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jArrivalLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jArrivalLocationActionPerformed

    private void jArrivalLocationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jArrivalLocationMouseClicked
        jArrivalLocation.setText("");
    }//GEN-LAST:event_jArrivalLocationMouseClicked

    private void jDepartureLcationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDepartureLcationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDepartureLcationActionPerformed

    private void jDepartureLcationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDepartureLcationMouseClicked
        jDepartureLcation.setText("");
    }//GEN-LAST:event_jDepartureLcationMouseClicked

    private void JFlightNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JFlightNumberActionPerformed

    }//GEN-LAST:event_JFlightNumberActionPerformed

    private void JFlightNumberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JFlightNumberMouseClicked
        JFlightNumber.setText("");
    }//GEN-LAST:event_JFlightNumberMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_addFlight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_addFlight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Create;
    private javax.swing.JTextField JFlightNumber;
    private javax.swing.JTextField jArrivalLocation;
    private javax.swing.JTextField jArrivalTime;
    private javax.swing.JTextField jDepartureLcation;
    private javax.swing.JTextField jDepartureTime;
    private javax.swing.JTextField jDestination;
    private javax.swing.JTextField jDistance;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLableAddFlight;
    private javax.swing.JTextField jOrigin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jStatus;
    // End of variables declaration//GEN-END:variables
}
