
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Omar Ismail
 */
public class gui_register extends javax.swing.JFrame {

    /**
     * Creates new form gui_register
     */
    public gui_register() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLablePassport = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jRegName = new javax.swing.JTextField();
        jRegAge = new javax.swing.JTextField();
        jRegEmail = new javax.swing.JTextField();
        jRegNationality = new javax.swing.JTextField();
        jRegUsername = new javax.swing.JTextField();
        jRegPassword = new javax.swing.JPasswordField();
        jRegPassport = new javax.swing.JTextField();
        jLableRegister = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        jLablePassport1 = new javax.swing.JLabel();
        jRadioMale = new javax.swing.JRadioButton();
        jRadioFemale = new javax.swing.JRadioButton();

        jLablePassport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLablePassport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLablePassport.setText("Passport:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(106, 0, 28));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Al_Mazerta_3.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 450));

        jButtonBack.setBackground(new java.awt.Color(106, 0, 28));
        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backabyadfinal.png"))); // NOI18N
        jButtonBack.setBorder(null);
        jButtonBack.setBorderPainted(false);
        jButtonBack.setContentAreaFilled(false);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(34, 45, 65));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(34, 45, 65));

        jRegName.setBackground(new java.awt.Color(34, 45, 65));
        jRegName.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegName.setForeground(new java.awt.Color(255, 255, 255));
        jRegName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("")), "Name :", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegName.setCaretColor(new java.awt.Color(34, 45, 65));
        jRegName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegNameMouseClicked(evt);
            }
        });
        jRegName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegNameActionPerformed(evt);
            }
        });

        jRegAge.setBackground(new java.awt.Color(34, 45, 65));
        jRegAge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegAge.setForeground(new java.awt.Color(255, 255, 255));
        jRegAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegAge.setText("\n");
        jRegAge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Age :", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegAge.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegAgeMouseClicked(evt);
            }
        });
        jRegAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegAgeActionPerformed(evt);
            }
        });

        jRegEmail.setBackground(new java.awt.Color(34, 45, 65));
        jRegEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegEmail.setForeground(new java.awt.Color(255, 255, 255));
        jRegEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Email :", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegEmailMouseClicked(evt);
            }
        });
        jRegEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegEmailActionPerformed(evt);
            }
        });

        jRegNationality.setBackground(new java.awt.Color(34, 45, 65));
        jRegNationality.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegNationality.setForeground(new java.awt.Color(255, 255, 255));
        jRegNationality.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegNationality.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nationality :", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegNationality.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegNationality.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegNationalityMouseClicked(evt);
            }
        });
        jRegNationality.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegNationalityActionPerformed(evt);
            }
        });

        jRegUsername.setBackground(new java.awt.Color(34, 45, 65));
        jRegUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegUsername.setForeground(new java.awt.Color(255, 255, 255));
        jRegUsername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegUsername.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Username :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegUsernameMouseClicked(evt);
            }
        });
        jRegUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegUsernameActionPerformed(evt);
            }
        });

        jRegPassword.setBackground(new java.awt.Color(34, 45, 65));
        jRegPassword.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegPassword.setForeground(new java.awt.Color(255, 255, 255));
        jRegPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegPassword.setText("PASSWORD");
        jRegPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Password :", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegPasswordMouseClicked(evt);
            }
        });
        jRegPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegPasswordActionPerformed(evt);
            }
        });

        jRegPassport.setBackground(new java.awt.Color(34, 45, 65));
        jRegPassport.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jRegPassport.setForeground(new java.awt.Color(255, 255, 255));
        jRegPassport.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRegPassport.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Passport number :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jRegPassport.setCaretColor(new java.awt.Color(255, 255, 255));
        jRegPassport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRegPassportMouseClicked(evt);
            }
        });
        jRegPassport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegPassportActionPerformed(evt);
            }
        });

        jLableRegister.setBackground(new java.awt.Color(0, 0, 0));
        jLableRegister.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLableRegister.setForeground(new java.awt.Color(255, 255, 255));
        jLableRegister.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLableRegister.setText("Register");
        jLableRegister.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLableRegister.setPreferredSize(new java.awt.Dimension(450, 450));

        Register.setBackground(new java.awt.Color(106, 0, 28));
        Register.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Register");
        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });

        jLablePassport1.setBackground(new java.awt.Color(95, 210, 195));
        jLablePassport1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLablePassport1.setForeground(new java.awt.Color(255, 255, 255));
        jLablePassport1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLablePassport1.setText("Gender:");

        buttonGroup1.add(jRadioMale);
        jRadioMale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioMale.setText("Male");
        jRadioMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioMaleActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioFemale);
        jRadioFemale.setForeground(new java.awt.Color(255, 255, 255));
        jRadioFemale.setText("Female");
        jRadioFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioFemaleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLablePassport1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jRadioMale, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRegName)
                            .addComponent(jRegAge)
                            .addComponent(jRegEmail)
                            .addComponent(jRegNationality)
                            .addComponent(jRegPassport)
                            .addComponent(jRegUsername)
                            .addComponent(jRegPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                        .addContainerGap(75, Short.MAX_VALUE))))
            .addComponent(jLableRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLableRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jRegName, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jRegAge, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jRegEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(jRegNationality, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jRegPassport, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addComponent(jRegUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jRegPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLablePassport1, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioMale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioFemale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Register, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButtonBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(84, 84, 84))
        );

        jPanel2.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRegNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegNameMouseClicked
        jRegName.setText("");
    }//GEN-LAST:event_jRegNameMouseClicked

    private void jRegNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegNameActionPerformed
    }//GEN-LAST:event_jRegNameActionPerformed

    private void jRegAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegAgeMouseClicked
        // TODO add your handling code here:
        jRegAge.setText("");
    }//GEN-LAST:event_jRegAgeMouseClicked

    private void jRegAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegAgeActionPerformed

    private void jRegEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegEmailMouseClicked
        // TODO add your handling code here:
        jRegEmail.setText("");
    }//GEN-LAST:event_jRegEmailMouseClicked

    private void jRegEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegEmailActionPerformed

    private void jRegNationalityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegNationalityMouseClicked
        // TODO add your handling code here:
        jRegNationality.setText("");
    }//GEN-LAST:event_jRegNationalityMouseClicked

    private void jRegNationalityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegNationalityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegNationalityActionPerformed

    private void jRegUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegUsernameMouseClicked
        // TODO add your handling code here:
        jRegUsername.setText("");
    }//GEN-LAST:event_jRegUsernameMouseClicked

    private void jRegUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegUsernameActionPerformed

    private void jRegPassportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegPassportMouseClicked
        // TODO add your handling code here:
        jRegPassport.setText("");
    }//GEN-LAST:event_jRegPassportMouseClicked

    private void jRegPassportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegPassportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegPassportActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        try {
            new gui_main().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        try {
            PersonsController per = new PersonsController();

            String register_username = (String) jRegUsername.getText();
            String register_email = (String) jRegEmail.getText();
            String register_password = new String(jRegPassword.getPassword());
            String register_name = (String) jRegName.getText();
            int register_age = Integer.parseInt(jRegAge.getText());
            String register_nationality = (String) jRegNationality.getText();
            String register_passport = (String) jRegPassport.getText();
            boolean register_frequentFlyer = false;
            int register_loyaltyPoints = 0;
            String register_gender = "";
            if (jRadioMale.isSelected()) {
                register_gender = "M";
            }
            if (jRadioFemale.isSelected()) {
                register_gender = "F";
            }

            per.addPassenger(register_name, register_age, register_gender, register_email, register_nationality,
                    register_username, register_password, register_passport, register_frequentFlyer, register_loyaltyPoints);

            String filePath = "src/Database.txt";
            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            content = content.trim();
            if (content.endsWith("]")) {
                if (content.length() > 1) {
                    content = content.substring(0, content.length() - 1).trim();
                    if (!content.isEmpty()) {
                        content += ",";
                    }
                }
                // Append the new JSON object
                content += "\n{\"name\":\"" + register_name + "\",\"age\":" + register_age + ",\"gender\":\"" + register_gender + "\",\"emil\":\"" + register_email + "\","
                        + "\"nationality\":\"" + register_nationality + "\",\"username\":\"" + register_username + "\",\"password\":\"" + register_password + "\","
                        + "\"type\":\"PASSENGER\",\"passenger\":{\"passportNumber\":\"" + register_passport + "\","
                        + "\"frequentFlyer\":" + register_frequentFlyer + ",\"loyaltyPoints\":" + register_loyaltyPoints + "},\"admin\":{\"department\":null,"
                        + "\"experience\":0,\"revenue\":0},\"seats\":[]}";

                content += "\n]";
            }
            
            BufferedWriter writer = new BufferedWriter(new FileWriter(filePath));
            writer.write(content);
            writer.close();
            System.out.println("New JSON object added to the array successfully.");

            new gui_login().setVisible(true);
            this.setVisible(false);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Something went wrong", "Something went wrong", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RegisterActionPerformed

    private void jRegPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRegPasswordMouseClicked
        jRegPassword.setText("");
    }//GEN-LAST:event_jRegPasswordMouseClicked

    private void jRegPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRegPasswordActionPerformed

    private void jRadioMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioMaleActionPerformed

    private void jRadioFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioFemaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui_register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLablePassport;
    private javax.swing.JLabel jLablePassport1;
    private javax.swing.JLabel jLableRegister;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioFemale;
    private javax.swing.JRadioButton jRadioMale;
    private javax.swing.JTextField jRegAge;
    private javax.swing.JTextField jRegEmail;
    private javax.swing.JTextField jRegName;
    private javax.swing.JTextField jRegNationality;
    private javax.swing.JTextField jRegPassport;
    private javax.swing.JPasswordField jRegPassword;
    private javax.swing.JTextField jRegUsername;
    // End of variables declaration//GEN-END:variables
}
