
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Omar Ismail
 */
public class gui_updateInfo extends javax.swing.JFrame {

    /**
     * Creates new form gui_updateInfo
     */
    public gui_updateInfo() throws Exception {
        load();
        initComponents();
        setLocationRelativeTo(null);
    }

    public void load() throws Exception {
        try {
            String filePathUsers = "src/Database.txt";
            ObjectMapper objectMapper = new ObjectMapper();
            String _users = new String(Files.readAllBytes(Paths.get(filePathUsers)));
            ArrayList<Person> pers = objectMapper.readValue(_users, new TypeReference<ArrayList<Person>>() {
            });
            Person.persons = pers;

        } catch (Exception e) {
            throw e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jBackButton = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jLabel13 = new javax.swing.JTextField();
        jUpdateEmail = new javax.swing.JTextField();
        jUpdatePass = new javax.swing.JTextField();
        jUpdateAge = new javax.swing.JTextField();
        jLableUpdate = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jUpdateUsername1 = new javax.swing.JTextField();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 45, 65));

        jBackButton.setBackground(new java.awt.Color(95, 210, 195));
        jBackButton.setText("Back");
        jBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBackButtonActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(95, 210, 195));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(34, 45, 65));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLabel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jLabel13.setMaximumSize(null);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        jLabel13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLabel13ActionPerformed(evt);
            }
        });

        jUpdateEmail.setBackground(new java.awt.Color(34, 45, 65));
        jUpdateEmail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUpdateEmail.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUpdateEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Email", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jUpdateEmail.setMaximumSize(null);
        jUpdateEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUpdateEmailMouseClicked(evt);
            }
        });
        jUpdateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateEmailActionPerformed(evt);
            }
        });

        jUpdatePass.setBackground(new java.awt.Color(34, 45, 65));
        jUpdatePass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUpdatePass.setForeground(new java.awt.Color(255, 255, 255));
        jUpdatePass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUpdatePass.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Password", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jUpdatePass.setMaximumSize(null);
        jUpdatePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUpdatePassMouseClicked(evt);
            }
        });
        jUpdatePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdatePassActionPerformed(evt);
            }
        });

        jUpdateAge.setBackground(new java.awt.Color(34, 45, 65));
        jUpdateAge.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUpdateAge.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUpdateAge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Age", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jUpdateAge.setMaximumSize(null);
        jUpdateAge.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUpdateAgeMouseClicked(evt);
            }
        });
        jUpdateAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateAgeActionPerformed(evt);
            }
        });

        jLableUpdate.setBackground(new java.awt.Color(255, 255, 255));
        jLableUpdate.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLableUpdate.setForeground(new java.awt.Color(95, 210, 195));
        jLableUpdate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLableUpdate.setText("Update Info");
        jLableUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/acclogin.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));

        jUpdateUsername1.setBackground(new java.awt.Color(34, 45, 65));
        jUpdateUsername1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jUpdateUsername1.setForeground(new java.awt.Color(255, 255, 255));
        jUpdateUsername1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jUpdateUsername1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update your login username", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jUpdateUsername1.setMaximumSize(null);
        jUpdateUsername1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUpdateUsername1MouseClicked(evt);
            }
        });
        jUpdateUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateUsername1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(474, 474, 474)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jUpdateEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jUpdatePass, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jUpdateAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                            .addComponent(jUpdateUsername1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(51, 51, 51)))
                        .addGap(22, 22, 22)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLableUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addGap(530, 530, 530))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLableUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(90, 90, 90)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jUpdateEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jUpdatePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jUpdateUsername1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jUpdateAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3)))
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateAgeActionPerformed

    }//GEN-LAST:event_jUpdateAgeActionPerformed

    private void jUpdateAgeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUpdateAgeMouseClicked
        jUpdateAge.setText("");
    }//GEN-LAST:event_jUpdateAgeMouseClicked

    private void jUpdatePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdatePassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdatePassActionPerformed

    private void jUpdatePassMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUpdatePassMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdatePassMouseClicked

    private void jUpdateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateEmailActionPerformed

    }//GEN-LAST:event_jUpdateEmailActionPerformed

    private void jUpdateEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUpdateEmailMouseClicked

    }//GEN-LAST:event_jUpdateEmailMouseClicked

    private void jLabel13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabel13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            PersonsController controller = new PersonsController();

            int age = Integer.parseInt(jUpdateAge.getText());
            String username = (String) jLabel13.getText();
            String password = (String) jUpdatePass.getText();
            String email = (String) jUpdateEmail.getText();
            String name = (String) jLabel13.getText();

            controller.updateAccount(age, password, username, email,name);

        } catch (IOException ex) {
            Logger.getLogger(gui_updateInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBackButtonActionPerformed
        try {
            new gui_passenger().setVisible(true);
            this.setVisible(false);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jBackButtonActionPerformed

    private void jUpdateUsername1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUpdateUsername1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateUsername1MouseClicked

    private void jUpdateUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateUsername1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui_updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui_updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui_updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui_updateInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new gui_updateInfo().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(gui_updateInfo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBackButton;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLableUpdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jUpdateAge;
    private javax.swing.JTextField jUpdateEmail;
    private javax.swing.JTextField jUpdatePass;
    private javax.swing.JTextField jUpdateUsername1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
